TYPE=VIEW
query=select `oxid`.`oxgroups`.`OXID` AS `OXID`,`oxid`.`oxgroups`.`OXACTIVE` AS `OXACTIVE`,`oxid`.`oxgroups`.`OXTITLE` AS `OXTITLE`,`oxid`.`oxgroups`.`OXTITLE_1` AS `OXTITLE_1`,`oxid`.`oxgroups`.`OXTITLE_2` AS `OXTITLE_2`,`oxid`.`oxgroups`.`OXTITLE_3` AS `OXTITLE_3`,`oxid`.`oxgroups`.`OXTIMESTAMP` AS `OXTIMESTAMP` from `oxid`.`oxgroups`
md5=0c588e5cb1c16bf9c4cf3dac84607fd5
updatable=1
algorithm=0
definer_user=oxid
definer_host=%
suid=0
with_check_option=0
timestamp=2024-09-05 12:52:36
create-version=1
source=SELECT oxgroups.OXID,oxgroups.OXACTIVE,oxgroups.OXTITLE,oxgroups.OXTITLE_1,oxgroups.OXTITLE_2,oxgroups.OXTITLE_3,oxgroups.OXTIMESTAMP FROM oxgroups
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `oxid`.`oxgroups`.`OXID` AS `OXID`,`oxid`.`oxgroups`.`OXACTIVE` AS `OXACTIVE`,`oxid`.`oxgroups`.`OXTITLE` AS `OXTITLE`,`oxid`.`oxgroups`.`OXTITLE_1` AS `OXTITLE_1`,`oxid`.`oxgroups`.`OXTITLE_2` AS `OXTITLE_2`,`oxid`.`oxgroups`.`OXTITLE_3` AS `OXTITLE_3`,`oxid`.`oxgroups`.`OXTIMESTAMP` AS `OXTIMESTAMP` from `oxid`.`oxgroups`
