TYPE=VIEW
query=select `oxid`.`oxselectlist`.`OXID` AS `OXID`,`oxid`.`oxselectlist`.`OXSHOPID` AS `OXSHOPID`,`oxid`.`oxselectlist`.`OXTITLE` AS `OXTITLE`,`oxid`.`oxselectlist`.`OXIDENT` AS `OXIDENT`,`oxid`.`oxselectlist`.`OXVALDESC` AS `OXVALDESC`,`oxid`.`oxselectlist`.`OXTITLE_1` AS `OXTITLE_1`,`oxid`.`oxselectlist`.`OXVALDESC_1` AS `OXVALDESC_1`,`oxid`.`oxselectlist`.`OXTITLE_2` AS `OXTITLE_2`,`oxid`.`oxselectlist`.`OXVALDESC_2` AS `OXVALDESC_2`,`oxid`.`oxselectlist`.`OXTITLE_3` AS `OXTITLE_3`,`oxid`.`oxselectlist`.`OXVALDESC_3` AS `OXVALDESC_3`,`oxid`.`oxselectlist`.`OXTIMESTAMP` AS `OXTIMESTAMP` from `oxid`.`oxselectlist`
md5=e49fb73afee024454afb65305a746523
updatable=1
algorithm=0
definer_user=oxid
definer_host=%
suid=0
with_check_option=0
timestamp=2024-09-05 12:52:36
create-version=1
source=SELECT oxselectlist.OXID,oxselectlist.OXSHOPID,oxselectlist.OXTITLE,oxselectlist.OXIDENT,oxselectlist.OXVALDESC,oxselectlist.OXTITLE_1,oxselectlist.OXVALDESC_1,oxselectlist.OXTITLE_2,oxselectlist.OXVALDESC_2,oxselectlist.OXTITLE_3,oxselectlist.OXVALDESC_3,oxselectlist.OXTIMESTAMP FROM oxselectlist
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `oxid`.`oxselectlist`.`OXID` AS `OXID`,`oxid`.`oxselectlist`.`OXSHOPID` AS `OXSHOPID`,`oxid`.`oxselectlist`.`OXTITLE` AS `OXTITLE`,`oxid`.`oxselectlist`.`OXIDENT` AS `OXIDENT`,`oxid`.`oxselectlist`.`OXVALDESC` AS `OXVALDESC`,`oxid`.`oxselectlist`.`OXTITLE_1` AS `OXTITLE_1`,`oxid`.`oxselectlist`.`OXVALDESC_1` AS `OXVALDESC_1`,`oxid`.`oxselectlist`.`OXTITLE_2` AS `OXTITLE_2`,`oxid`.`oxselectlist`.`OXVALDESC_2` AS `OXVALDESC_2`,`oxid`.`oxselectlist`.`OXTITLE_3` AS `OXTITLE_3`,`oxid`.`oxselectlist`.`OXVALDESC_3` AS `OXVALDESC_3`,`oxid`.`oxselectlist`.`OXTIMESTAMP` AS `OXTIMESTAMP` from `oxid`.`oxselectlist`
