TYPE=VIEW
query=select `oxid`.`oxgroups`.`OXID` AS `OXID`,`oxid`.`oxgroups`.`OXACTIVE` AS `OXACTIVE`,`oxid`.`oxgroups`.`OXTITLE` AS `OXTITLE`,`oxid`.`oxgroups`.`OXTIMESTAMP` AS `OXTIMESTAMP` from `oxid`.`oxgroups`
md5=c6bf693039011f63f7c28ac4b46bebca
updatable=1
algorithm=0
definer_user=oxid
definer_host=%
suid=0
with_check_option=0
timestamp=2024-09-05 12:52:36
create-version=1
source=SELECT oxgroups.OXID AS OXID,oxgroups.OXACTIVE AS OXACTIVE,oxgroups.OXTITLE AS OXTITLE,oxgroups.OXTIMESTAMP AS OXTIMESTAMP FROM oxgroups
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `oxid`.`oxgroups`.`OXID` AS `OXID`,`oxid`.`oxgroups`.`OXACTIVE` AS `OXACTIVE`,`oxid`.`oxgroups`.`OXTITLE` AS `OXTITLE`,`oxid`.`oxgroups`.`OXTIMESTAMP` AS `OXTIMESTAMP` from `oxid`.`oxgroups`
