TYPE=VIEW
query=select `oxid`.`oxdeliveryset`.`OXID` AS `OXID`,`oxid`.`oxdeliveryset`.`OXSHOPID` AS `OXSHOPID`,`oxid`.`oxdeliveryset`.`OXACTIVE` AS `OXACTIVE`,`oxid`.`oxdeliveryset`.`OXACTIVEFROM` AS `OXACTIVEFROM`,`oxid`.`oxdeliveryset`.`OXACTIVETO` AS `OXACTIVETO`,`oxid`.`oxdeliveryset`.`OXTITLE` AS `OXTITLE`,`oxid`.`oxdeliveryset`.`OXTITLE_1` AS `OXTITLE_1`,`oxid`.`oxdeliveryset`.`OXTITLE_2` AS `OXTITLE_2`,`oxid`.`oxdeliveryset`.`OXTITLE_3` AS `OXTITLE_3`,`oxid`.`oxdeliveryset`.`OXPOS` AS `OXPOS`,`oxid`.`oxdeliveryset`.`OXTIMESTAMP` AS `OXTIMESTAMP`,`oxid`.`oxdeliveryset`.`OXTRACKINGURL` AS `OXTRACKINGURL` from `oxid`.`oxdeliveryset`
md5=f9c9bdef433004edf2a2794f7f89cdbc
updatable=1
algorithm=0
definer_user=oxid
definer_host=%
suid=0
with_check_option=0
timestamp=2024-09-05 12:52:36
create-version=1
source=SELECT oxdeliveryset.OXID,oxdeliveryset.OXSHOPID,oxdeliveryset.OXACTIVE,oxdeliveryset.OXACTIVEFROM,oxdeliveryset.OXACTIVETO,oxdeliveryset.OXTITLE,oxdeliveryset.OXTITLE_1,oxdeliveryset.OXTITLE_2,oxdeliveryset.OXTITLE_3,oxdeliveryset.OXPOS,oxdeliveryset.OXTIMESTAMP,oxdeliveryset.OXTRACKINGURL FROM oxdeliveryset
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `oxid`.`oxdeliveryset`.`OXID` AS `OXID`,`oxid`.`oxdeliveryset`.`OXSHOPID` AS `OXSHOPID`,`oxid`.`oxdeliveryset`.`OXACTIVE` AS `OXACTIVE`,`oxid`.`oxdeliveryset`.`OXACTIVEFROM` AS `OXACTIVEFROM`,`oxid`.`oxdeliveryset`.`OXACTIVETO` AS `OXACTIVETO`,`oxid`.`oxdeliveryset`.`OXTITLE` AS `OXTITLE`,`oxid`.`oxdeliveryset`.`OXTITLE_1` AS `OXTITLE_1`,`oxid`.`oxdeliveryset`.`OXTITLE_2` AS `OXTITLE_2`,`oxid`.`oxdeliveryset`.`OXTITLE_3` AS `OXTITLE_3`,`oxid`.`oxdeliveryset`.`OXPOS` AS `OXPOS`,`oxid`.`oxdeliveryset`.`OXTIMESTAMP` AS `OXTIMESTAMP`,`oxid`.`oxdeliveryset`.`OXTRACKINGURL` AS `OXTRACKINGURL` from `oxid`.`oxdeliveryset`
