TYPE=VIEW
query=select `oxid`.`oxdeliveryset`.`OXID` AS `OXID`,`oxid`.`oxdeliveryset`.`OXSHOPID` AS `OXSHOPID`,`oxid`.`oxdeliveryset`.`OXACTIVE` AS `OXACTIVE`,`oxid`.`oxdeliveryset`.`OXACTIVEFROM` AS `OXACTIVEFROM`,`oxid`.`oxdeliveryset`.`OXACTIVETO` AS `OXACTIVETO`,`oxid`.`oxdeliveryset`.`OXTITLE` AS `OXTITLE`,`oxid`.`oxdeliveryset`.`OXPOS` AS `OXPOS`,`oxid`.`oxdeliveryset`.`OXTIMESTAMP` AS `OXTIMESTAMP`,`oxid`.`oxdeliveryset`.`OXTRACKINGURL` AS `OXTRACKINGURL` from `oxid`.`oxdeliveryset`
md5=b2d30146a677d68c17d3b0c9182d3729
updatable=1
algorithm=0
definer_user=oxid
definer_host=%
suid=0
with_check_option=0
timestamp=2024-09-05 12:52:36
create-version=1
source=SELECT oxdeliveryset.OXID AS OXID,oxdeliveryset.OXSHOPID AS OXSHOPID,oxdeliveryset.OXACTIVE AS OXACTIVE,oxdeliveryset.OXACTIVEFROM AS OXACTIVEFROM,oxdeliveryset.OXACTIVETO AS OXACTIVETO,oxdeliveryset.OXTITLE AS OXTITLE,oxdeliveryset.OXPOS AS OXPOS,oxdeliveryset.OXTIMESTAMP AS OXTIMESTAMP,oxdeliveryset.OXTRACKINGURL AS OXTRACKINGURL FROM oxdeliveryset
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `oxid`.`oxdeliveryset`.`OXID` AS `OXID`,`oxid`.`oxdeliveryset`.`OXSHOPID` AS `OXSHOPID`,`oxid`.`oxdeliveryset`.`OXACTIVE` AS `OXACTIVE`,`oxid`.`oxdeliveryset`.`OXACTIVEFROM` AS `OXACTIVEFROM`,`oxid`.`oxdeliveryset`.`OXACTIVETO` AS `OXACTIVETO`,`oxid`.`oxdeliveryset`.`OXTITLE` AS `OXTITLE`,`oxid`.`oxdeliveryset`.`OXPOS` AS `OXPOS`,`oxid`.`oxdeliveryset`.`OXTIMESTAMP` AS `OXTIMESTAMP`,`oxid`.`oxdeliveryset`.`OXTRACKINGURL` AS `OXTRACKINGURL` from `oxid`.`oxdeliveryset`
