version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./source:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oxid
      MYSQL_USER: oxid
      MYSQL_PASSWORD: oxid
    volumes:
      - ./mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - "8080:8080"